Repository the-virtual-brain/tvb-root, pull requests merged in 2022-10, with the labels that each got.

#595 TVB-2513 CI: Adjust usage of cache
  .github/workflows/build.yml
  .github/workflows/pg-tests.yml
Labels: bug, area/framework

#596 TVB-2513 Address the setuptools issue in builds
  .github/workflows/build.yml
  .github/workflows/pg-tests.yml
Labels: bug, area/framework

#594 TVB-2946 Adjust sample rate in wavelet to be in kHz
  tvb_library/tvb/analyzers/wavelet.py
  tvb_library/tvb/datatypes/time_series.py
Labels: bug, area/scilib

#569 tvb-contrib changes by DP
  tvb_contrib/tvb/contrib/cosimulation/cosimulator.py
  tvb_contrib/tvb/contrib/scripts/datatypes/time_series.py
  tvb_contrib/tvb/contrib/scripts/datatypes/time_series_xarray.py
  tvb_contrib/tvb/contrib/scripts/plot/power_spectra_coherence_interactive.py
  tvb_contrib/tvb/contrib/scripts/utils/data_structures_utils.py
  tvb_contrib/tvb/contrib/scripts/utils/time_series_utils.py
  tvb_library/tvb/simulator/plot/config.py
  tvb_library/tvb/simulator/plot/power_spectra_interactive.py
  tvb_library/tvb/simulator/plot/time_series_plotter.py
Labels: area/scilib

#600 HBP-198 Declare some plots deprecated under tvb-library
  tvb_build/docker/requirements_group
  tvb_contrib/tvb/contrib/scripts/plot/power_spectra_coherence_interactive.py
  tvb_documentation/demos/3d-plotting.ipynb
  tvb_documentation/sim_doc/class_diagrams.sh
  tvb_documentation/sim_doc/img/classes_phase_plane_interactive.svg
  tvb_documentation/sim_doc/img/classes_power_spectra_interactive.svg
  tvb_documentation/sim_doc/img/classes_timeseries_interactive.svg
  tvb_documentation/sim_doc/tvb.simulator.plot.phase_plane_interactive.rst
  tvb_documentation/sim_doc/tvb.simulator.plot.power_spectra_interactive.rst
  tvb_documentation/sim_doc/tvb.simulator.plot.timeseries_interactive.rst
  tvb_documentation/sim_doc/tvb.simulator.rst
  tvb_library/requirements.txt
  tvb_library/setup.py
  tvb_library/tvb/simulator/plot/head_plotter.py
  tvb_library/tvb/simulator/plot/head_plotter_3d.py
  tvb_library/tvb/simulator/plot/phase_plane_interactive.py
  tvb_library/tvb/simulator/plot/power_spectra_interactive.py
  tvb_library/tvb/simulator/plot/time_series_plotter.py
  tvb_library/tvb/simulator/plot/timeseries_interactive.py
Labels: documentation, area/scilib

#603 HBP-196. HBP-195. Fixes for OpenShift deploy
  tvb_build/docker/Dockerfile-run
  tvb_build/docker/requirements_group
  tvb_build/hbp_openshift_deployer/tvb_deployer.yml
  tvb_framework/requirements.txt
  tvb_framework/tvb/interfaces/web/controllers/decorators.py
  tvb_framework/tvb/interfaces/web/operation_openshift_assigner.py
  tvb_storage/tvb/storage/h5/encryption/data_encryption_handler.py
  tvb_storage/tvb/storage/kube/kube_notifier.py
Labels: area/framework

#589 (GSoC 2022, 8.2) TVB BIDS data builder and dir monitor module
  tvb_framework/MANIFEST_bids_monitor.in
  tvb_framework/setup_bids_monitor.py
  tvb_framework/tvb/adapters/uploaders/bids_importer.py
  tvb_framework/tvb/interfaces/rest/bids_monitoring/README.md
  tvb_framework/tvb/interfaces/rest/bids_monitoring/bids_data_builder.py
  tvb_framework/tvb/interfaces/rest/bids_monitoring/bids_dir_monitor.py
  tvb_framework/tvb/interfaces/rest/bids_monitoring/launch_bids_monitor.py
  tvb_framework/tvb/tests/framework/interfaces/rest/bids_data_builder_test.py
  tvb_framework/tvb/tests/framework/interfaces/rest/bids_dir_monitor_test.py
Labels: good first issue, area/framework, gsoc contribution

#606 TVB-3036. Fix tests.
  tvb_build/docker/requirements_group
  tvb_framework/requirements.txt
  tvb_framework/setup_bids_monitor.py
Labels: area/framework

#607 TVB-3037 Fix DirLoader.load
  tvb_framework/tvb/core/neocom/_h5loader.py
  tvb_framework/tvb/core/neocom/h5.py
  tvb_framework/tvb/interfaces/command/demos/datatypes/store_into_h5.py
  tvb_framework/tvb/tests/framework/core/neocom_test.py
Labels: bug, area/framework

#608 TVB-3036. Review tests.
  tvb_build/package_for_pip.sh
  tvb_framework/README_bids_monitor.rst
  tvb_framework/setup_bids_monitor.py
  tvb_framework/tvb/interfaces/rest/bids_monitor/bids_data_builder.py
  tvb_framework/tvb/interfaces/rest/bids_monitor/bids_dir_monitor.py
  tvb_framework/tvb/interfaces/rest/bids_monitor/launch_bids_monitor.py
  tvb_framework/tvb/tests/framework/interfaces/rest/bids_data_builder_test.py
  tvb_framework/tvb/tests/framework/interfaces/rest/bids_dir_monitor_test.py
  tvb_framework/tvb/tests/framework/interfaces/rest/bids_monitor_test.py
Labels: gsoc contribution

#602 HBP-189 Fix tests in tvb-contrib related to cosimulation
  tvb_contrib/tvb/contrib/cosimulation/cosimulator.py
  tvb_contrib/tvb/contrib/tests/cosimulation/parallel/modify_wongwang_precision_test.py
  tvb_contrib/tvb/contrib/tests/cosimulation/parallel/monitors_test.py
  tvb_contrib/tvb/contrib/tests/cosimulation/parallel/update_function_test.py
  tvb_contrib/tvb/contrib/tests/cosimulation/simple/modify_wongwang_precision_test.py
  tvb_contrib/tvb/contrib/tests/cosimulation/simple/modify_wongwang_test.py
  tvb_contrib/tvb/contrib/tests/cosimulation/synchronization_time_set.py
Labels: bug, area/scilib

#604 HBP-199. Move/add tests from tvb-multiscale to tvb-contrib
  .github/workflows/lib-tests.yml
  tvb_contrib/pytest.ini
  tvb_contrib/tvb/contrib/tests/model/model_test.py
  tvb_contrib/tvb/contrib/tests/scripts/__init__.py
  tvb_contrib/tvb/contrib/tests/scripts/time_series_test.py
Labels: enhancement, area/scilib
