Repository the-virtual-brain/tvb-root, pull requests merged in 2023-04, with the labels that each got.

#661 TVB-3078 Create a redirect in the Pypi package "tvb" towards "tvb-library"
  tvb_deprecated/setup.py
  tvb_library/setup.py
Labels: area/scilib

#666 TVB-2847: run notebooks automatically from a github worflow
  .github/workflows/notebooks.yml
  tvb_build/notebook_runner.py
  tvb_documentation/demos/encrypt_data.ipynb
  tvb_documentation/demos/exploring_K_ION_Exchange_model.ipynb
  tvb_documentation/demos/interacting_with_the_framework.ipynb
  tvb_documentation/demos/public_key.pem
  tvb_documentation/demos/simulate_for_mouse.ipynb
  tvb_documentation/demos/simulate_zerlaut.ipynb
  tvb_framework/tvb/interfaces/command/lab.py
Labels: area/scilib, area/framework

#660 HBP-184: Create an YML template file that generates a backup cronjob in OKD
  tvb_build/hbp_openshift_deployer/README
  tvb_build/hbp_openshift_deployer/tvb_backup.yml
  tvb_build/hbp_openshift_deployer/tvb_deployer.yml
Labels: area/framework

#665 HBP-222: create a template that starts a tvb-storage backup cronjob
  tvb_build/hbp_openshift_deployer/README
  tvb_build/hbp_openshift_deployer/tvb_backup_db.yml
  tvb_build/hbp_openshift_deployer/tvb_backup_storage.yml
Labels: area/framework

#657 TVB-2118: add a function that sets the console's logging level
  tvb_documentation/demos/compare_connectivity_normalization.ipynb
  tvb_documentation/demos/using_your_own_connectivity.ipynb
  tvb_library/tvb/basic/logger/builder.py
  tvb_library/tvb/simulator/common.py
  tvb_library/tvb/simulator/lab.py
Labels: enhancement, area/scilib

#573 WIP: AdEx model update
  tvb_documentation/demos/adex_meanfied/adex_meanfield.ipynb
  tvb_documentation/demos/adex_meanfied/cfgs/carlu2020.toml
  tvb_documentation/demos/adex_meanfied/cfgs/divolo2019.toml
  tvb_documentation/demos/adex_meanfied/cfgs/goldman2020.toml
  tvb_documentation/demos/adex_meanfied/goldman_2020_spontaneous_activity.ipynb
  tvb_documentation/demos/adex_meanfied/utils.py
  tvb_documentation/demos/simulate_zerlaut.ipynb
  tvb_library/tvb/simulator/models/zerlaut.py
Labels: area/scilib

#669 Small fixes to Zerlaut form and labels, for PhasePlane usage
  tvb_framework/tvb/adapters/forms/model_forms.py
  tvb_library/tvb/simulator/models/zerlaut.py
Labels: area/framework
